lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Adrien Coulier
  description: Pipeline to QC your sequences
  force: false
  is_nfcore: true
  name: seqinspector
  org: nf-core
  outdir: .
  version: 1.0dev
